CREATE EXTERNAL TABLE IF NOT EXISTS mtg_cards(
name STRING,
multiverseid STRING,
type STRING,
imageUrl STRING
) COMMENT 'MTG Cards'
ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS
TEXTFILE LOCATION '/user/hadoop/mtg/final';
